# Generated by Django 4.2.21 on 2025-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
