# Generated by Django 4.2.21 on 2025-05-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_options_remove_contact_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
